services:

  exchnager:
    build:
      context: .
    container_name: front
    restart: always
    ports:
      - "80:80"
    volumes:
      - static:/var/www/static
      - ./log:/var/log/nginx





